apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: h9igcrtqv-nodejs 
  janus-idp.io/tekton: h9igcrtqv-nodejs
  backstage.io/kubernetes-id: h9igcrtqv-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: h9igcrtqv-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml